####################### START OF SQL SCRIPT ######################
#                                                                #                                          
# DAY # : 44                                                     #                                  
#                                                                #
# THIS SCRIPT IS USED FOR HOSPITAL MANAGEMENT WHICH MAINTAINS    #
# THE DETAILS ABOUT THE USER AND THEIR ROLE AND ALSO ABOUT THE   #
# DETAILS OF PATIENT AND THE DOCTOR WHO TAKES CARE OF THEM AND   #
# THE DIAGNOSIS PROVIDED BY THEM.                                #
#                                                                #
# AUTHOR : DHARINI SHREE K                                       #                                                          
#                                                                #
######################## END OF SQL SCRIPT #######################

/*CREATING A DATABASE HOSPITAL MANAGEMENT TO HOLD THE DETAILS OF PATIENTS AND THE DOCTORS 
AND THEIR PAYMENT.*/

CREATE DATABASE HOSPITAL_MANAGEMENT;
USE HOSPITAL_MANAGEMENT;

/*CREATING A TABLE ROLE WHICH CONSISTS OF ROLES OF PERSONS WHO CAN ACCESS THE SYSTEM.*/

CREATE TABLE ROLE(
ID INT PRIMARY KEY,
ROLENAME VARCHAR(15) NOT NULL
);

/*CREATING A TABLE USER WHICH IS USED FOR REGISTERING THE DETAILS OF THE ADMINS INTO THE SYSTEM.*/

CREATE TABLE USER
(
ID INT PRIMARY KEY,
EMAILID VARCHAR(30) UNIQUE,
PASSWORD VARCHAR(30) NOT NULL,
ROLEID INT,
FOREIGN KEY (ROLEID) REFERENCES ROLE(ID)
);

/*INSERTING THE VALUES OF ROLES INTO THE ROLE TABLE.*/

INSERT INTO ROLE(ID,ROLENAME) VALUES(1,"ADMIN");
INSERT INTO ROLE(ID,ROLENAME) VALUES(2,"HOSPITAL ADMIN");

/*CREATING A TABLE PATIENTDETAILS WHICH CONSISTS OF THE DETAIS OF PATIENTS LIKE THEIR NAME,
DOB, CONTACT DETAILS, STATE AND ALSO ABOUT THEIR MEDICAL INSURANCE.*/

CREATE TABLE PATIENTDETAILS
(
ID INT PRIMARY KEY,
FIRSTNAME VARCHAR(20) NOT NULL,
LASTNAME VARCHAR(20) NOT NULL,
DATEOFBIRTH DATE NOT NULL,
EMAILID VARCHAR(30) UNIQUE NOT NULL,
CONTACTNUMBER INT NOT NULL,
STATE VARCHAR(30),
INSURANCEPLAN VARCHAR(30)
);

/*CREATING A TABLE PHYSICIANDETAILS WHICH CONSISTS OF THE DETAIS OF PATIENTS LIKE THEIR NAME,
DEPARTMENT,QUALIFICATIONS,YEARS OF EXPERIENCE,STATE,INSURANCEPLANS.*/

CREATE TABLE PHYSICIANDETAILS
(
PHYSICIANID VARCHAR(30) UNIQUE,
FIRSTNAME VARCHAR(20) NOT NULL,
LASTNAME VARCHAR(20) NOT NULL,
DEPARTMENT VARCHAR(10) NOT NULL,
EDUCATIONALQUALIFICATION VARCHAR(10) NOT NULL,
YEARSOFEXPERIENCE INT NOT NULL,
STATE VARCHAR(30),
INSURANCEPLAN VARCHAR(30),
PATIENTID INT REFERENCES PATIENTDETAILS(ID)
);

/*CREATING A TABLE DIAGNOSTICDETAILS WHICH CONSISTS OF PATIENTSID,DIAGNOSTICID,PHYSICIAN NAME,
DATE OF DIAGNOSIS,DATE OF FOLLOW UP,AMOUNT TO BE PAID,MODE OF PAYMENT 
AND THE CARD NUMBER IN CASE OF ONLINE PAYMENT.*/

CREATE TABLE DIAGNOSTICDETAILS
( 
PATIENTID INT,
FOREIGN KEY (PATIENTID) REFERENCES PATIENTDETAILS(ID),
DIAGNOSTICID VARCHAR(30) UNIQUE,
SYMPTOMS VARCHAR(20) NOT NULL,
DIAGNOSISPROVIDED VARCHAR(20),
PHYSICIANID INT REFERENCES PHYSICIANDETAILS(PHYSICIANID),
DATEOFDIAGNOSIS DATE NOT NULL,
FOLLOWUP BOOLEAN,
DATEOFFOLLOWUP DATE,
BILLAMOUNT DOUBLE NOT NULL,
CARDNUMBER VARCHAR(30) NOT NULL,
MODEOFPAYAMENT VARCHAR(10)
);


 
